device: cuda
exp_num: 
path: "/path/to/save/exps"
th_seed:
np_seed:

model:
  pad_size: 15

dataloader:
  wm_paths: [["/path/to/wall_pressure_data",
            "/path/to/wall_dudy_data",
            "/path/to/wall_dwdy_data"]]
  vf_paths: [["/path/to/u_data",
            "/path/to/v_data",
            "/path/to/w_data"]]
  batch_size: 32
  time_cutoff: 36000
  jump: null
  dataset: WMVF_baseline
  scale_inputs: False
  wm_vf : False # False for vf -> wm, True for wm -> vf

optimizer:
  lr: 1e-3

num_epochs: 100
print_epoch_int: 1
save_epoch_int: 5
print_with_epoch_int: 10
# rolling_steps: 3
restart: False
restart_epoch: